version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production
    assignees:
      - "fabiankachlock"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
